csdnblog/blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'


urlpatterns = [
    path('index',views.index,name='index'),
    path('blog/detail/<int:blog_id>' ,views.blog_detail,name='blog_detail'),
    path('blog/pub',views.pub_blog,name='pub_blog'),
    path('blog/comment/pub',views.pub_comment,name='pub_comment'),
    path('search' ,views.search,name='search'),
]

csdnblog/csdnblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('auth/', include('yinauth.urls')),

]

csdnblog/yinauth/urls.py
from django.urls import path
from .import views


app_name = 'yinauth'
urlpatterns = [
    path('login', views.yinlogin, name='login'),
    path('logout', views.yinlogout, name='logout'),
    path('register', views.register, name='register'),
    path('email/captcha',views.send_email, name='email_captcha'),

]

csdnblog/templates/base.html
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>{% block title %}Yin_BLOG{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="{% static 'bootstrap5/bootstrap.min.css' %}"></script>
    
    {% block head %}{% endblock %}

</head>
<body>
<header class="p-3 text-bg-warning border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/static" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/logo.png' %}" alt="" height=40>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-2">
                <li><a href="/index" class="nav-link px-2 text-secondary">First Page</a></li>
                <li><a href="{% url 'blog:pub_blog' %}" class="nav-link px-2 text-secondary">Public Blog</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search'%}">
                <input type="search" name="q" class="form-control form-control-dark text-bg-light" placeholder="Search..."
                       aria-label="Search">
            </form>



            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle show"
                       data-bs-toggle="dropdown" aria-expanded="True">
                        <img src="{% static 'image/avatar.webp' %}" alt="mdo" width="32" height="32"
                             class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small show"
                        style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(0px, 34px, 0px);"
                        data-popper-placement="bottom-start">
                        <li><a class="dropdown-item" href="{% url 'yinauth:logout' %}">退出登录</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="text-end">
                    <a href="{% url 'yinauth:login' %}" type="button" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'yinauth:register' %}" type="button" class="btn btn-primary">注册</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded  bg-white">
    {% block main %}{% endblock %}
</main>
</body>
</html>



 

csdnblog/templates/blog_detail.html
{% extends 'base.html' %}
{% block head %}
	<link rel="stylesheet" href="{% static 'highlight/styles/default.min.css' %}">
    <script src=" {% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}

{% block main %}
        <h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" width="30" height="30" alt="">
        <span class="ms-2">{{ blog.author.username }}</span>
        <span class="ms-2">于</span>
        <span class="ms-2">{{ blog.pub_time|date:"Y年m月d日 h时i分s" }}</span>发布
    </div>
    <hr>
    <div class="py-2">
        {{ blog.content |safe }}
    </div>
    <hr>
    <div class="mt-2">
        <h3>{{ blog.comments.all | length }}</h3>
      
        <form action="{% url 'blog:pub_comment' %}" method="POST">
              {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请留下您的想法" name="content">
            </div>
            
            <div class="text-end mt-2">
                <button type="button" class="btn btn-primary ">评论</button>

            </div>
            <div class="mt-2">
                <ul class="list-group list-group-flush">
                    {% for comment in blog.comments.all %}
                    <li class="list-group-item mb-2">
                        <div class="d-flex justify-content-between text-body-secondary">
                            <div class="user-info">
                                <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" width="40"
                                     height="40" alt="">
                                <span class="ms-2">{{ comment.author.username }}</span>
                            </div>
                            <div class="creat_time " style="line-height:40px">{{ blog.pub_time|date:"Y年m月d日 h时i分s" }}</div>
                            
                        </div>
                        <div class='mt-2'>{{ comment.content }}</div>
                    </li>
                    {% endfor %}
                    
                </ul>

            </div>

        </form>
    </div>
    <script>
   hljs.highlightAll();
    </script>
{% endblock%}

csdnblog/templates/index.html
{% extends 'base.html' %}

{% block title %}FirstPage{% endblock %}

{% block main %}
    <h1>Blog List</h1>
    <div class="row row-cols-2 row-gap-4">
    {% for blog in blogs %}
        <div class="cols">
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'blog:blog_detail' blog_id=blog.id %}">{{ blog.title }}</a>
                </div>
                <div class="card-body" style="height: 100px;">

                    <p class="card-text">{{ blog.content | striptags |truncatechars:100 }}</p>

                </div>
                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" width="30" height="30"
                             alt={{ blog.author.username }}>
                    </div>
                    <div>发布时间: {{ blog.pub_time|date:"Y年m月d日 h时i分s" }}</div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    </body>
    </html>
{% endblock %}




 

csdnblog/templates/login.html
{% extends 'base.html' %}

{% block title %}login{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class=m-auto"">
        <h1>login</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    remember
                </label>
            </div>
            <div class="mb-3">
                <button class="btn btn-primary w-100">立即登录</button>
            </div>
        </form>
    </div>
{% endblock %}

csdnblog/templates/pub_blog.html
{% extends 'base.html' %}
{% block title %} 发布博客{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static  'wangeditor/style.css' %}">
    <script src=" {% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>

{% endblock %}

{% block main %}
    <h1>发布博客</h1>
    <div class="mt-3">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">标题</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">分类</label>
                <select name="category" class="form-select" id="category-select">
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">内容</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3 text-end">
                <button class="btn btn-primary" id="submit-btn">发布</button>
            </div>
        </form>
    </div>
{% endblock %}

csdnblog/templates/register.html
{% extends 'base.html' %}

{% block title %}register{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class=m-auto"">
        <h1>register</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>用户名</label>
                <input type="text" name="username" class="form-control" placeholder="用户名">
            </div>
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <label>验证码</label>
            <div class="input-group">
                <input type="text" class="form-control" name="captcha" placeholder="验证码"
                       aria-label="Recipient's username" aria-describedby="button-addon2">
                <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
            </div>


            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="mb-3">
                <button class="btn btn-primary w-100">立即注册</button>
            </div>
        </form>
    </div>


{% endblock %}